export enum MessageType {
  CHAT = 'CHAT',
  UNSEEN = 'UNSEEN',
  FRIEND_ONLINE = 'FRIEND_ONLINE',
  FRIEND_OFFLINE = 'FRIEND_OFFLINE',
  MESSAGE_DELIVERY_UPDATE = 'MESSAGE_DELIVERY_UPDATE',
  FRIEND_REQUEST = 'FRIEND_REQUEST'
}
